name: "Common operations"
description: "do something common for all test"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: download zookeeper
      uses: actions/cache@v3
      with:
        path: apache-zookeeper-3.6.3-bin.tar.gz
        key: ${{ runner.os }}-apache-zookeeper-3.6.3
    - name: run zookeeper
      shell: bash
      run: |
        tar -zxf apache-zookeeper-3.6.3-bin.tar.gz
        bash apache-zookeeper-3.6.3-bin/bin/zkServer.sh start apache-zookeeper-3.6.3-bin/conf/zoo_sample.cfg
    - name: download local cse
      uses: actions/cache@v3
      with:
        path: Local-CSE-2.1.3-linux-amd64.zip
        key: ${{ runner.os }}-local-cse
        restore-keys: |
          ${{ runner.os }}-local-cse
    - name: start cse
      shell: bash
      run: |
        export ROOT_PATH=$(pwd)
        bash ./sermant-integration-tests/scripts/startCse.sh
    - name: download agent
      uses: actions/cache@v3
      with:
        path: sermant-agent-*/
        key: ${{ runner.os }}-agent-${{ github.run_id }}
