name: "Spring Common Test"
description: "Auto test for spring common, include flowcontrol, loadbalancer, boot-registry, cloud-registry"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: download local cse
      uses: actions/cache@v3
      with:
        path: Local-CSE-2.1.3-linux-amd64.zip
        key: ${{ runner.os }}-local-cse
        restore-keys: |
          ${{ runner.os }}-local-cse
    - name: start cse
      shell: bash
      run: |
        export ROOT_PATH=$(pwd)
        bash ./sermant-integration-tests/scripts/startCse.sh
    - name: download zookeeper
      uses: actions/cache@v3
      with:
        path: apache-zookeeper-3.6.3-bin.tar.gz
        key: ${{ runner.os }}-apache-zookeeper-3.6.3
    - name: run zookeeper
      shell: bash
      run: |
        tar -zxf apache-zookeeper-3.6.3-bin.tar.gz
        bash apache-zookeeper-3.6.3-bin/bin/zkServer.sh start apache-zookeeper-3.6.3-bin/conf/zoo_sample.cfg
    - name: download agent
      uses: actions/cache@v3
      with:
        path: sermant-agent-*/
        key: ${{ runner.os }}-agent-${{ github.run_id }}
    - name: 1.5.x config
      if: matrix.springBootVersion == '1.5.0.RELEASE' && matrix.springCloudVersion == 'Edgware.SR2'
      shell: bash
      run: |
        echo "tailVersion=-1.5.x" >> $GITHUB_ENV
    - name: package common demos
      shell: bash
      run: |
        sed -i 's|<version>${{ env.projectSpringBootVersion }}</version>|<version>${{ matrix.springBootVersion }}</version>|g' sermant-integration-tests/spring-test/pom.xml
        mvn package -Dspring.cloud.version=${{ matrix.springCloudVersion }} -Dspring.boot.version=${{ matrix.springBootVersion }} -DskipTests -P common-test{{ env.tailVersion }} --file sermant-integration-tests/spring-test/pom.xml
    - name: start applications
      shell: bash
      env:
        dynamic.config.serverAddress: 127.0.0.1:30110
        dynamic.config.dynamicConfigType: KIE
        service.meta.environment: development
        sermant.springboot.registry.enableRegistry: true
      run: |
        mkdir logs
        nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=default -Dservice.meta.application=feign -Dserver.port=8013 -jar \
        -Dsermant_log_dir=./logs/feign-provider${{ env.tailVersion }}\
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign-1.5.x/feign-provider-1.5.x/target/feign-provider-1.5.x.jar > feign-provider.log 2>&1 &
        nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=default -Dservice.meta.application=feign -Dserver.port=8014 \
        -Dsermant_log_dir=./logs/feign-provider-8014${{ env.tailVersion }}-Dservicecomb.service.enableSpringRegister=true -jar \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign-1.5.x/feign-provider-1.5.x/target/feign-provider-1.5.x.jar > feign-provider-8014.log 2>&1 &
        nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=default -Dservice.meta.application=feign -Dserver.port=8015 -jar \
        -Dsermant_log_dir=./logs/feign-consumer${{ env.tailVersion }}-Dservicecomb.service.openMigration=true -Dservicecomb.service.enableSpringRegister=true \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign-1.5.x/feign-consumer-1.5.x/target/feign-consumer-1.5.x.jar > feign-consumer.log 2>&1 &
        nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=default -Dservice.meta.application=rest -Dserver.port=8003 -jar \
        -Dsermant_log_dir=./logs/rest-provider${{ env.tailVersion }}\
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-provider/target/rest-provider.jar > rest-provider.log 2>&1 &
        nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=default -Dservice.meta.application=rest -Dserver.port=8004 -jar \
        -Dsermant_log_dir=./logs/rest-provider${{ env.tailVersion }}-Dservicecomb.service.enableSpringRegister=true \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-provider/target/rest-provider.jar > rest-provider-8004.log 2>&1 &
        nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=default -Dservice.meta.application=rest -Dserver.port=8005 -jar \
        -Dsermant_log_dir=./logs/rest-consumer${{ env.tailVersion }}-Dconfig.retry.sleepMs=20 -Dservicecomb.service.openMigration=true -Dservicecomb.service.enableSpringRegister=true \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-consumer/target/rest-consumer.jar > rest-consumer.log 2>&1 &
        ls -l ./logs
    - name: waiting for services start
      shell: bash
      run: |
        ps -ef | grep java
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8015/flowcontrol/rateLimiting 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8005/flowcontrol/rateLimiting 60
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8005/lb/ping 60
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8004/rateLimiting 60
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8014/rateLimiting 60
    - name: integration test module FLOW_CONTROL
      shell: bash
      run: mvn test -Dsermant.integration.test.type=FLOW_CONTROL --file sermant-integration-tests/spring-test/pom.xml
    - name: integration test module LOAD_BALANCER
      shell: bash
      run: mvn test -Dsermant.integration.test.type=LOAD_BALANCER -Dspring.boot.version=${{ matrix.springBootVersion }} --file sermant-integration-tests/spring-test/pom.xml
    - name: integration test module BOOT_REGISTRY
      shell: bash
      if: matrix.springBootVersion == '1.5.0.RELEASE' && matrix.springCloudVersion == 'Edgware.SR2'
      run: mvn test -Dsermant.integration.test.type=BOOT_REGISTRY -Dapp.version=1.5.x -Dspring.boot.version=${{ matrix.springBootVersion }} --file sermant-integration-tests/spring-test/pom.xml
    - name: integration test module BOOT_REGISTRY
      shell: bash
      if: matrix.springBootVersion != '1.5.0.RELEASE' && matrix.springCloudVersion != 'Edgware.SR2'
      run: mvn test -Dsermant.integration.test.type=BOOT_REGISTRY -Dspring.boot.version=${{ matrix.springBootVersion }} -Dhttp.client.version=${{ matrix.httpClientVersion }} --file sermant-integration-tests/spring-test/pom.xml
    - name: integration test module CLOUD_REGISTRY
      shell: bash
      run: mvn test -Dsermant.integration.test.type=CLOUD_REGISTRY --file sermant-integration-tests/spring-test/pom.xml
    - name: if failure then upload error log
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: (${{ github.job }})-(${{ matrix.springBootVersion }}-${{ matrix.springCloudVersion }})-logs
        path: |
          ./*.log
          ./logs/**/*.log
        if-no-files-found: warn
        retention-days: 5
