name: docker images test
on:
  push:
  pull_request:
    branches:
      - main
      - develop
jobs:
  test-kie:
    name: use kie
    runs-on: ubuntu-latest
    services:
      kie:
        image: servicecomb/kie:0.2.1
        ports:
          - 30110:30110
    steps:
      - name: test kie
        run: |
          sleep 10
          curl localhost:30110
