name: docker images test
on:
  push:
  pull_request:
    branches:
      - main
      - develop
jobs:
  test-kie:
    name: pull kie
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - name: test
        uses: actions/checkout@v3
        with:
          repository: apache/servicecomb-kie
      - name: build kie
        run: |
          ls -l
          echo "=============当前路径$(pwd)=========="
          echo "============构建脚本================"
          export PROJECT_PATH=$(pwd)
          export VERSION=0.2.0
          cd ./build
          cat > test.sh <<EOF
          . ./build_binary.sh
          echo "building docker..."
          buildAndPackage "linux" "amd64"
          echo "=====当前路径$(pwd)=========="
          cp ${PROJECT_PATH}/scripts/start.sh ./
          cp ${PROJECT_PATH}/build/docker/server/Dockerfile ./
          sudo docker version
          sudo docker build -t servicecomb/test-kie:${VERSION} .
          EOF
          sudo chmod 777 *.sh
          echo "================删除最后9行=============="
          for((i=1;i<9;i++)); do sed -i '$d' ./build_binary.sh ; done
          tail -n 6 ./build_binary.sh
          echo "================删除完成================="
          ls -l
          echo "=========执行脚本==========="
          set -x
          sh ./test.sh
          docker images
