name: docker images test
on:
  push:
  pull_request:
    branches:
      - main
      - develop
jobs:
  test-kie:
    name: pull kie
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: actions/checkout@v3
        with:
          repository: apache/servicecomb-kie
        run: |
          ls -l
#          git clone git@github.com:apache/servicecomb-kie.git
#          cd servicecomb-kie/deployments/docker
#          sudo docker-compose up
