name: docker images test
on:
  push:
  pull_request:
    branches:
      - main
      - develop
jobs:
  test-kie:
    name: pull kie
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - name: test
        uses: actions/checkout@v3
        with:
          repository: apache/servicecomb-kie
      - name: build kie
        run: |
          cd build
          cat > test.sh <<EOF
          . ./build_binary.sh

          echo "building docker..."
          buildAndPackage "linux" "amd64"
          cp ../scripts/start.sh ./
          cp ../build/docker/server/Dockerfile ./

          sudo docker version
          sudo docker build -t servicecomb/kie:latest .
          sudo docker tag servicecomb/kie:latest servicecomb/kie:${version}
          EOF

          cd build
          export VERSION=0.0.1
          sh ./build_docker.sh
          docker images
