name: intergration spring test

on:
  push:
  pull_request:
    branches:
      - master
      - develop
jobs:
  test-for-spring-config:
    name: Test for spring config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: download nacos server and run
        run: |
          curl -o nacos-server-1.4.2.tar.gz -L https://github.com/alibaba/nacos/releases/download/1.4.2/nacos-server-1.4.2.tar.gz
          tar -zxf nacos-server-1.4.2.tar.gz
          bash nacos/bin/startup.sh -m standalone
      - name: download localcse and run
        run: |
          curl -o Local-CSE-2.1.3-linux-amd64.zip -L https://cse-bucket.obs.cn-north-1.myhuaweicloud.com/LocalCSE/Local-CSE-2.1.3-linux-amd64.zip
          unzip Local-CSE-2.1.3-linux-amd64.zip -d cse
          sh cse/start.sh &
      - name: package agent
        run: mvn package -DskipTests -Pagent --file pom.xml
      - name: package spring nacos config
        run: mvn package -DskipTests --file sermant-integration-tests/spring-test/pom.xml
      - name: start service with disable origin config center
        env:
          dynamic.config.serverAddress: 127.0.0.1:30110
          dynamic.config.dynamicConfigType: KIE
          dynamic.config.plugin.enableOriginConfigCenter: false
          dynamic.config.plugin.enableDynamicConfig: true
          server.port: 8989
        run: |
          nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=default -jar sermant-integration-tests/spring-test/spring-nacos-config/target/nacos-config.jar > nacos-config.log 2>&1 &
      - name: waiting for services start
        run: |
          ps -ef | grep java
          sleep 10
          curl http://127.0.0.1:8989/dynamic/config/check
      - name: integration test
        run: mvn test --file sermant-integration-tests/spring-test/pom.xml
      - name: start service with enable origin config center
        env:
          dynamic.config.serverAddress: 127.0.0.1:30110
          dynamic.config.dynamicConfigType: KIE
          dynamic.config.plugin.enableOriginConfigCenter: true
          dynamic.config.plugin.enableDynamicConfig: true
          server.port: 8989
        run: |
          ps -ef | grep java | awk '{print $1}' | xargs -n 1 | kill -9
          sh cse/stop.sh
          rm -rf cse/data
          sh cse/start.sh &
          nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=default -jar sermant-integration-tests/spring-test/spring-nacos-config/target/nacos-config.jar &
          sleep 10
          mvn test --file sermant-integration-tests/spring-test/pom.xml
